# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jekyll Demo
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  This demo blog bases on a template created by ruby 2.3.0p0 and jekyll
  3.1.2 on my Raspberry Pi. My propose of creating this demo blog is going
  to learn Git commands and Jekyll framework and LaTeX in HTML.
baseurl: /jekyll_demo # the subpath of your site, e.g. /blog
url: "http://pferdchen.github.io" # the base hostname & protocol for your site
twitter_username: gaoyan126
github_username:  Pferdchen

# Build settings
markdown: kramdown
