# Site settings
title: Jekyll Demo
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  This demo blog bases on a template created by ruby 2.2.1p85 and jekyll
  2.5.3 on my Raspberry Pi. My propose of creating this demo blog is going
  to learn git commands and Jekyll framework and LaTeX in HTML.
baseurl: /jekyll_demo # the subpath of your site, e.g. /blog/
url: "http://pferdchen.github.io" # the base hostname & protocol for your site
twitter_username: gaoyan126
github_username:  Pferdchen

# Build settings
markdown: kramdown
